### ISSUE TITLE
Console Error Spam

### ISSUE THREAD

**Issue by MrLiam2614** [ploppyperson/StackMob-5#294]
We recently upgraded from 1.20.1 to 1.20.6 (waiting for a sub version of 1.21) but we noticed that the console keeps spamming errors like this:

```
[20:22:26 WARN]: [StackMob] Task #267 for StackMob v5.9.2 generated an exception
java.lang.IllegalArgumentException: No enum constant uk.antiperson.stackmob.config.EntityConfig.NameTagStackMode.DONT_JOIN
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.craftbukkit.legacy.FieldRename.valueOf(FieldRename.java:57) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at StackMob-5.9.2.jar/uk.antiperson.stackmob.config.EntityConfig$NameTagStackMode.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_legacy_FieldRename_valueOf(EntityConfig.java) ~[StackMob-5.9.2.jar:?]
        at StackMob-5.9.2.jar/uk.antiperson.stackmob.config.EntityConfig$NameTagStackMode.valueOf(EntityConfig.java:411) ~[StackMob-5.9.2.jar:?]
        at StackMob-5.9.2.jar/uk.antiperson.stackmob.config.EntityConfig.getNameTagStackMode(EntityConfig.java:344) ~[StackMob-5.9.2.jar:?]
        at StackMob-5.9.2.jar/uk.antiperson.stackmob.entity.StackEntity.dropNameTag(StackEntity.java:342) ~[StackMob-5.9.2.jar:?]
        at StackMob-5.9.2.jar/uk.antiperson.stackmob.entity.StackEntity.merge(StackEntity.java:332) ~[StackMob-5.9.2.jar:?]
        at StackMob-5.9.2.jar/uk.antiperson.stackmob.tasks.MergeTask.checkEntity(MergeTask.java:60) ~[StackMob-5.9.2.jar:?]
        at StackMob-5.9.2.jar/uk.antiperson.stackmob.tasks.MergeTask.lambda$run$0(MergeTask.java:105) ~[StackMob-5.9.2.jar:?]
        at StackMob-5.9.2.jar/uk.antiperson.stackmob.tasks.MergeTask.run(MergeTask.java:109) ~[StackMob-5.9.2.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at java.base/java.lang.Thread.run(Thread.java:1595) ~[?:?]
```

Also, somtimes some mobs are stacked but you cannot even se the "tag" over their head (eg: "10x Zombie" etc..), sometimes you do

**Comment by ploppyperson** [comment]
DONT_JOIN isn't a valid nametag-mode.
